# -*- coding: utf-8 -*-
"""sistema-moderacao-ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLNXzh2v1Gz8tG6oUhbn3sCP9KeTCnR9
"""

from google.colab import auth
auth.authenticate_user()

import os
import uuid
from google.colab import userdata
from google import genai
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from typing import TypedDict, Optional
from IPython.display import Image, display

try:
    if "GOOGLE_API_KEY" not in os.environ:
        os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')
        print("✅ API Key configurada.")
except Exception as e:
    print("⚠️ Erro: Verifique se você criou o segredo 'GOOGLE_API_KEY' no Colab.")

client = genai.Client(api_key=os.environ["GOOGLE_API_KEY"])
MODELO = "gemini-2.5-flash"

class EstadoHibrido(TypedDict):
    texto: str
    status_moderacao: str
    motivo_bloqueio: Optional[str]
    analise_ia: Optional[str]
    revisao_ia: Optional[str]
    resultado_final: Optional[str]

def node_moderador(state: EstadoHibrido):
    """Filtro Rápido (Python): Barra ofensas óbvias."""
    print(f"🛡️ (Filtro): Verificando palavras proibidas...")
    texto_lower = state['texto'].lower()
    palavras_proibidas = ["idiota", "burro", "lixo", "golpe", "roubar", "fraude"]

    if any(p in texto_lower for p in palavras_proibidas):
        return {
            "status_moderacao": "Bloqueado",
            "motivo_bloqueio": "Linguagem ofensiva ou suspeita detectada."
        }
    return {"status_moderacao": "Aprovado"}

def node_analista(state: EstadoHibrido):
    """Agente de Risco: Focado em identificar anomalias financeiras."""
    print(f"🤖 (Analista de Risco): Auditando transação...")

    prompt = f"""
Atue como um Analista de Prevenção a Fraudes Sênior de um banco corporativo.

Analise a solicitação: "{state['texto']}"

DIRETRIZES DE SEGURANÇA (RIGOROSAS):
1. "Fornecedor Novo" + Valor Alto (>10k) = ALTO RISCO (Suspeita de fraude ou desvio).
2. Linguagem vaga ou informal = ALERTA AMARELO.
3. Jamais elogie a transação. Seja frio e técnico.

Sua saída deve listar os riscos identificados e recomendar: APROVAR, REJEITAR ou INVESTIGAR.
Não use formatação markdown complexa, seja direto.
    """

    try:
        response = client.models.generate_content(model=MODELO, contents=prompt)
        texto_resp = response.text
        return {"analise_ia": texto_resp}
    except Exception as e:
        return {"analise_ia": f"Erro técnico na IA: {str(e)}"}

def node_revisor(state: EstadoHibrido):
    """Agente de Compliance: Valida se a análise de risco foi suficiente."""
    print("🧐 (Compliance): Revisando parecer do analista...")

    prompt = f"""
Atue como Auditor de Compliance.
O Analista de Risco reportou: "{state['analise_ia']}"

Sua tarefa:
1. Se houver menção a "Novo Fornecedor" e valores altos, você DEVE recomendar a retenção para validação humana.
2. Seja extremamente conservador. O objetivo é proteger o capital do banco.

Resuma seu parecer final em uma frase curta e séria.
    """

    try:
        response = client.models.generate_content(model=MODELO, contents=prompt)
        texto_resp = response.text
        return {"revisao_ia": texto_resp}
    except Exception as e:
        return {"revisao_ia": "Erro na revisão."}

def node_executor(state: EstadoHibrido):
    """Nó Final: Simula a execução."""
    print("🚀 (Core Bancário): Processando transferência...")
    return {"resultado_final": "✅ Operação Concluída: Transferência realizada com sucesso!"}

workflow = StateGraph(EstadoHibrido)

workflow.add_node("moderador", node_moderador)
workflow.add_node("analista", node_analista)
workflow.add_node("revisor", node_revisor)
workflow.add_node("executor", node_executor)

workflow.set_entry_point("moderador")

def roteador_moderacao(state: EstadoHibrido):
    if state["status_moderacao"] == "Bloqueado":
        return "fim_bloqueado"
    return "seguir_para_ia"

workflow.add_conditional_edges("moderador", roteador_moderacao, {"fim_bloqueado": END, "seguir_para_ia": "analista"})
workflow.add_edge("analista", "revisor")
workflow.add_edge("revisor", "executor")
workflow.add_edge("executor", END)

checkpointer = MemorySaver()
graph = workflow.compile(checkpointer=checkpointer, interrupt_before=["executor"])

display(Image(graph.get_graph().draw_mermaid_png()))

texto_input = "Gostaria de transferir 50 mil reais para fornecedor novo"

thread_id = str(uuid.uuid4())
config = {"configurable": {"thread_id": thread_id}}

print(f"--- 🏦 INICIANDO AUDITORIA DE TRANSAÇÃO (ID: {thread_id[:8]}) ---")

for event in graph.stream({"texto": texto_input}, config):
    pass

snapshot = graph.get_state(config)

if snapshot.values:
    estado_atual = snapshot.values

    if estado_atual.get("status_moderacao") == "Bloqueado":
        print(f"\n❌ BLOQUEIO AUTOMÁTICO: {estado_atual.get('motivo_bloqueio')}")

    elif estado_atual.get("revisao_ia"):
        print("\n" + "="*70)
        print(f"🛑 PAUSA DE SEGURANÇA: ALERTA DE COMPLIANCE")
        print(f"💰 Solicitação: '{estado_atual['texto']}'")
        print("-" * 70)
        print(f"📋 Parecer Técnico (Analista): \n{estado_atual.get('analise_ia').strip()}")
        print("-" * 70)
        print(f"⚖️ Parecer Final (Compliance): {estado_atual.get('revisao_ia').strip()}")
        print("="*70)

        print("\nPAINEL DE DECISÃO DO GESTOR:")
        print(" [A] APROVAR (Assumir Risco)")
        print(" [R] REJEITAR (Seguir Compliance)")
        print(" [E] EDITAR/JUSTIFICAR (Inserir Override)")

        decisao = input("\n➡️ Decisão do Gestor: ").strip().lower()

        if decisao == "r":
            print("\n🚫 Transação REJEITADA pelo Gestor.")

        elif decisao == "e":
            print("\n✍️ MODO DE JUSTIFICATIVA (OVERRIDE)")
            print("Insira a justificativa para liberar ou alterar a transação.")
            nova_justificativa = input("   Justificativa: ")

            print("💾 Registrando justificativa no log de auditoria...")

            graph.update_state(config, {"revisao_ia": f"[GESTOR LIBEROU]: {nova_justificativa}"})

            print("\n--- Processando Liberação Manual ---")
            for event in graph.stream(None, config):
                if "resultado_final" in event.get("executor", {}):
                    print(f"\n{event['executor']['resultado_final']}")

        elif decisao == "a":
            print("\n--- Aprovado pelo Gestor. Executando... ---")

            for event in graph.stream(None, config):
                if "resultado_final" in event.get("executor", {}):
                    print(f"\n{event['executor']['resultado_final']}")

        else:
            print("\n❌ Comando inválido. Operação cancelada.")